sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - unzip
            - cmake
            - libboost-dev
            - libboost-all-dev
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get install -y doxygen
  - pip install --user cpp-coveralls
  - git clone https://github.com/simgrid/simgrid.git
  - cd simgrid
  - sudo cmake -Denable_documentation=OFF -Denable_coverage=OFF -Denable_java=OFF -Denable_model-checking=OFF -Denable_lua=OFF -Denable_compile_optimizations=OFF -Denable_smpi=OFF -Denable_smpi_MPICH3_testsuite=OFF -Denable_compile_warnings=OFF .
  - sudo make
  - sudo make install
  - cd ..

  - git clone
  
  - wget -O csvparser.zip https://sourceforge.net/projects/cccsvparser/files/2016-03-28/CsvParser_2016_03_28.zip/download
  - unzip csvparser.zip
  - cd CsvParser
  - mkdir lib
  - gcc -Iinclude src/csvparser.c -fPIC -shared -o lib/libcsvparser.so
  - sudo cp lib/libcsvparser.so /usr/lib
  - sudo cp include/csvparser.h /usr/include
  - cd ..

install:
  - sudo apt install -y lcov
  - gem install coveralls-lcov

script:
  - sudo cmake -DCMAKE_CXX_COMPILER=$COMPILER . && sudo make
  - sudo ./run.sh --enable-gcov

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
