sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - unzip
            - cmake
            - libboost-dev
            - libboost-all-dev
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get install -y doxygen
  - pip install --user cpp-coveralls
  - git clone https://github.com/simgrid/simgrid.git
  - cd simgrid
  - git reset --hard 37f351e6ee37d1073e4f409cd802b7065e2c12d9
  - sudo cmake -Denable_documentation=OFF -Denable_coverage=OFF -Denable_java=OFF -Denable_model-checking=OFF -Denable_lua=OFF -Denable_compile_optimizations=OFF -Denable_smpi=OFF -Denable_smpi_MPICH3_testsuite=OFF -Denable_compile_warnings=OFF .
  - sudo make
  - sudo make install
  - cd ..

  - git clone https://github.com/jbeder/yaml-cpp yaml-cpp
  - cd yaml-cpp
  - mkdir build
  - cd build
  - sudo cmake -DBUILD_SHARED_LIBS=ON ..
  - sudo make
  - sudo make install
  - sudo ldconfig
  - cd ../..

#install:
#  - sudo apt install -y lcov
#  - gem install coveralls-lcov

script:
  - ./run.sh

#after_success:
#  - lcov --directory . --capture --output-file coverage.info
#  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
#  - lcov --list coverage.info
